# Generated by Django 5.0.14 on 2025-09-26 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('make', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('trim', models.CharField(blank=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mileage_km', models.PositiveIntegerField(default=0)),
                ('exterior_color', models.CharField(blank=True, max_length=120)),
                ('interior_color', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=2)),
                ('city', models.CharField(max_length=120)),
                ('drivetrain', models.CharField(blank=True, choices=[('FWD', 'Front-wheel drive'), ('RWD', 'Rear-wheel drive'), ('AWD', 'All-wheel drive')], max_length=10)),
                ('dc_fast_charge_type', models.CharField(blank=True, choices=[('CCS', 'CCS'), ('NACS', 'NACS'), ('CHAdeMO', 'CHAdeMO'), ('TESLA', 'Tesla Proprietary'), ('UNKNOWN', 'Unknown')], max_length=12)),
                ('range_km', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_capacity_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('battery_warranty_years', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_warranty_km', models.PositiveIntegerField(blank=True, null=True)),
                ('has_heat_pump', models.BooleanField(default=False)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending moderation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, help_text='Comma separated marketing tags', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='dealers.dealerprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('internal_notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='listings.listing')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ModelSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('trim', models.CharField(blank=True, max_length=120)),
                ('year', models.PositiveSmallIntegerField()),
                ('battery_capacity_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('usable_battery_capacity_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('range_km', models.PositiveIntegerField(blank=True, null=True)),
                ('drivetrain', models.CharField(blank=True, choices=[('FWD', 'Front-wheel drive'), ('RWD', 'Rear-wheel drive'), ('AWD', 'All-wheel drive')], max_length=10)),
                ('dc_fast_charge_type', models.CharField(blank=True, choices=[('CCS', 'CCS'), ('NACS', 'NACS'), ('CHAdeMO', 'CHAdeMO'), ('TESLA', 'Tesla Proprietary'), ('UNKNOWN', 'Unknown')], max_length=12)),
                ('heat_pump_standard', models.BooleanField(default=False)),
                ('onboard_charger_kw', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('seating_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('make', 'model', 'trim', 'year'),
                'unique_together': {('make', 'model', 'trim', 'year')},
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.modelspec'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'province', 'city'], name='listings_li_status_ed9dde_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['make', 'model', 'year'], name='listings_li_make_3d327f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='listings_li_created_92fa22_idx'),
        ),
    ]
