# Generated by Django 5.0.14 on 2025-09-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='derivatives',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='photo',
            name='original_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='original_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
