# Generated by Django 5.0.14 on 2025-09-26 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('province', models.CharField(blank=True, max_length=64)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('hero_image', models.ImageField(blank=True, upload_to='dealers/hero/')),
                ('logo', models.ImageField(blank=True, upload_to='dealers/logo/')),
                ('is_featured', models.BooleanField(default=False)),
                ('inventory_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dealer profile',
                'verbose_name_plural': 'Dealer profiles',
                'ordering': ('name',),
            },
        ),
    ]
